service: root-gateway

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

resources:
  Resources:
    HttpApiGateway:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: main-http-api
        ProtocolType: HTTP
  Outputs:
    HttpApiId:
      Value: !Ref HttpApiGateway
      Export:
        Name: HttpApiId
